name: todo_auth_client
description: Client app for the todo auth service

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^5.1.2
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
