name: todo_auth_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dart_frog: ^0.2.0
  dart_jsonwebtoken: ^2.5.0
  equatable: ^2.0.5
  meta: ^1.8.0
  mongo_dart: ^0.8.0
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
